import {
  FACT_BOUNDARY_POLICY,
  HUMAN_WRITING_STYLE_POLICY,
  JSON_OUTPUT_POLICY,
  MOBILE_READING_STYLE_POLICY,
  ROLE_POLICY,
  RUNTIME_INPUT_POLICY,
  SOURCE_USAGE_POLICY,
  WORKFLOW_CONTINUITY_POLICY,
} from "./policies";

export const WRITING_SYSTEM_PROMPT = [
  ROLE_POLICY,
  "在任何阶段的交互和生成中，你必须绝对服从以下全局铁律：",
  FACT_BOUNDARY_POLICY,
  SOURCE_USAGE_POLICY,
  RUNTIME_INPUT_POLICY,
  WORKFLOW_CONTINUITY_POLICY,
  HUMAN_WRITING_STYLE_POLICY,
  MOBILE_READING_STYLE_POLICY,
  JSON_OUTPUT_POLICY,
].join("\n\n");
